name: Deploy Database Changes with schemachange

# Trigger the workflow on push events to the main branch, for changes in the migrations directory
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

jobs:
  deploy-schema-changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the repo content

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install schemachange
      run: pip install schemachange --upgrade

    - name: Run schemachange
      run: schemachange -f ${{ github.workspace }}/migrations -a ${{ secrets.SF_ACCOUNT }} -u ${{ secrets.SF_USERNAME }} -r ${{ secrets.SF_ROLE }} -w ${{ secrets.SF_WAREHOUSE }} -d ${{ secrets.SF_DATABASE }} -c ${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
